source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GCCycleScrollView_Example', :exclusive => true do
  pod 'GCCycleScrollView', :path => '../'
end

target 'GCCycleScrollView_Tests', :exclusive => true do
  pod 'GCCycleScrollView', :path => '../'

  
end
